# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: wayblue-sway-nvidia-trimmed
description: Trimmed wayblue, some additions.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/wayblueorg/sway-nvidia
image-version: 42 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    repos:
      -  https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
      -  https://copr.fedorainfracloud.org/coprs/alternateved/eza/repo/fedora-%OS_VERSION%/alternateved-eza-fedora-%OS_VERSION%.repo
      -  https://copr.fedorainfracloud.org/coprs/codifryed/CoolerControl/repo/fedora-%OS_VERSION%/codifryed-CoolerControl-fedora-%OS_VERSION%.repo
    install:
      - alacritty
      - bat
      - btrfs-assistant
      - conda
      - coolercontrol
      - flatpak-spawn
      - htop
      - intel-vaapi-driver
      - lshw
      - nvtop
      - easyeffects
      - eza
      - fd-find
      - fish
      - gammastep
      - keychain
      - liquidctl
      - lm_sensors
      - ncdu
      - neovim
      - rclone
      - smartmontools
      - squashfs-tools
      - tmux
      - wireguard-tools
      - snapper
      - starship
      - symlinks
      - tcpdump
      - vnstat
      - zstd
      - https://deploy.totallyacdn.com/desktop-apps/2.14.12/windscribe_2.14.12_x86_64_fedora.rpm
      - https://github.com/sigstore/cosign/releases/download/v2.5.0/cosign-2.5.0-1.x86_64.rpm
    remove:
      ## Wayblue

      # sway-modules.yml
      - foot
      # sddm-modules.yml
      - kwallet
      - pam-kwallet
      # common-modules.yml
      - google-noto-emoji-fonts
      - fontawesome-fonts-all
      - gnome-themes-extra
      - gnome-icon-theme
      - paper-icon-theme

      ## Fedora atomic images

      # Fedora-specific packages 
      - fedora-bookmarks
      - fedora-chromium-config
      - fedora-flathub-remote
      - fpaste

      # proj-data not sure what is pulling in
      - proj-data-ar
      - proj-data-at
      - proj-data-au
      - proj-data-be
      - proj-data-br
      - proj-data-ca
      - proj-data-ch
      - proj-data-cz
      - proj-data-de
      - proj-data-dk
      - proj-data-es
      - proj-data-eur
      - proj-data-fi
      - proj-data-fo
      - proj-data-fr
      - proj-data-hu
      - proj-data-is
      - proj-data-jp
      - proj-data-lv
      - proj-data-mx
      - proj-data-nc
      - proj-data-nl
      - proj-data-no
      - proj-data-nz
      - proj-data-pl
      - proj-data-pt
      - proj-data-se
      - proj-data-si
      - proj-data-sk
      - proj-data-uk
      - proj-data-us
      - proj-data-za

      # Unneeded fonts, ibus engines
      - default-fonts-cjk-mono
      - default-fonts-cjk-sans
      - default-fonts-cjk-serif
      - ibus-anthy
      - ibus-anthy-python
      - ibus-hangul
      - ibus-libpinyin
      - ibus-chewing

      # Misc
      - brltty
      - orca
      - firefox
      - firefox-langpacks
      - toolbox # using distrobox
      - spice-webdavd
      - spice-vdagent

  - type: fonts
    fonts:
      nerd-fonts:
        - JetBrainsMono

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

  - type: initramfs
